name: Build My App

on: push

jobs:
  build:
    name: Build our App
    runs-on: ubuntu-latest

    steps:
      - name: Pull code
        uses: actions/checkout@v4

      - name: Print Current Directory
        run: pwd

      - name: List files in Directory
        run: ls

      - name: Check Dotnet Cli
        run: dontnet build

      - name: List files in Directory
        run: ls Tricking.Library.Api/ -R

      - name: Check NPM Cli
        run: npm -v