name: Build My App

on: push

jobs:
  build:
    name: Build our App
    runs-on: ubuntu-latest

    steps:
      - name: Pull code
        uses: actions/checkout@v4

      - name: Print Current Directory
        run: pwd

      - name: List files in Directory
        run: ls
      - name: Check Dotnet Cli
        run: ls
      - name: Check NPM Cli
        run: ls