name: Build My App

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    name: Build our App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Print Current Directory
        run: pwd

      - name: List files in Directory
        run: ls